ktor:
  application:
    modules:
      - org.delcom.ApplicationKt.module
  deployment:
    # Mengambil nilai dari System.setProperty("APP_PORT") yang ada di main()
    port: ${APP_PORT}
    # Mengambil nilai dari System.setProperty("APP_HOST") yang ada di main()
    host: ${APP_HOST}